In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key
import gmaps.datasets

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Rengo,CL,2021-03-19 17:10:22,-34.4167,-70.8667,66.20,55,75,9.22
1,1,Saskylakh,RU,2021-03-19 17:10:22,71.9167,114.0833,-32.12,97,0,4.72
2,2,Saint-Philippe,RE,2021-03-19 17:10:22,-21.3585,55.7679,77.00,83,75,18.41
3,3,Balkanabat,TM,2021-03-19 17:10:22,39.5108,54.3671,59.38,45,24,5.75
4,4,Ribeira Grande,PT,2021-03-19 17:10:23,38.5167,-28.7000,62.60,82,75,17.27

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [ ]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
# heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
heat_layer = gmaps.heatmap_layer(locations, weights=temps, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

In [7]:
# Heatmap of percent humidity
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
# Get the maximum temperature.
#max_temp = city_data_df["Humidity"]
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
# Get the maximum temperature.

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent cloudiness
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
# Get the maximum temperature.

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [18]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Saint-Philippe,RE,2021-03-19 17:10:22,-21.3585,55.7679,77.00,83,75,18.41
8,8,Manggar,ID,2021-03-19 17:10:23,-2.8833,108.2667,79.75,82,15,4.68
13,13,Ormara,PK,2021-03-19 17:10:24,25.2088,64.6357,76.12,73,0,8.16
15,15,Nioki,CD,2021-03-19 17:10:25,-2.7167,17.6833,76.55,86,100,1.54
20,20,Rikitea,PF,2021-03-19 17:10:26,-23.1203,-134.9692,80.33,76,100,12.71
28,28,Sinnamary,GF,2021-03-19 17:10:28,5.3833,-52.9500,81.45,68,40,8.48
33,33,Puerto Escondido,MX,2021-03-19 17:10:29,15.8500,-97.0667,84.20,74,1,4.61
36,36,Trelew,AR,2021-03-19 17:05:35,-43.2490,-65.3051,82.45,16,0,16.62
37,37,Conceicao Do Araguaia,BR,2021-03-19 17:10:30,-8.2578,-49.2647,78.64,86,98,5.91
38,38,Puerto Ayora,EC,2021-03-19 17:10:30,-0.7393,-90.3518,82.40,78,20,9.22

In [23]:
preferred_cities_df.count()

City_ID       185
City          185
Country       185
Date          185
Lat           185
Lng           185
Max Temp      185
Humidity      185
Cloudiness    185
Wind Speed    185
dtype: int64

In [24]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

                     City Country  Max Temp      Lat       Lng Hotel Name
2          Saint-Philippe      RE     77.00 -21.3585   55.7679
8                 Manggar      ID     79.75  -2.8833  108.2667
13                 Ormara      PK     76.12  25.2088   64.6357
15                  Nioki      CD     76.55  -2.7167   17.6833
20                Rikitea      PF     80.33 -23.1203 -134.9692
28              Sinnamary      GF     81.45   5.3833  -52.9500
33       Puerto Escondido      MX     84.20  15.8500  -97.0667
36                 Trelew      AR     82.45 -43.2490  -65.3051
37  Conceicao Do Araguaia      BR     78.64  -8.2578  -49.2647
38           Puerto Ayora      EC     82.40  -0.7393  -90.3518

In [29]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
  # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
# Grab the first hotel from the results and store the name.
       
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [31]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Saint-Philippe,RE,77.00,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
8,Manggar,ID,79.75,-2.8833,108.2667,Guest Hotel
13,Ormara,PK,76.12,25.2088,64.6357,Crystal Beach and Camping Resort Ormara
15,Nioki,CD,76.55,-2.7167,17.6833,
20,Rikitea,PF,80.33,-23.1203,-134.9692,Pension Maro'i
28,Sinnamary,GF,81.45,5.3833,-52.9500,ALETHEIA Appartement Sinnamary
33,Puerto Escondido,MX,84.20,15.8500,-97.0667,Aldea del Bazar Hotel and Spa
36,Trelew,AR,82.45,-43.2490,-65.3051,Hotel Touring Club
37,Conceicao Do Araguaia,BR,78.64,-8.2578,-49.2647,Tarumã Tropical Hotel
38,Puerto Ayora,EC,82.40,-0.7393,-90.3518,Finch Bay Galapagos Hotel

In [32]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [34]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [35]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))